-- sql/009_create_table_guides.sql
CREATE TABLE IF NOT EXISTS Esports (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    api_id VARCHAR(100) NULL,
    category_name VARCHAR(50) NULL,
    score DECIMAL(10,2) NULL,
    type VARCHAR(50) NULL,
    name VARCHAR(150) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (api_id, name)
);
